### ISSUE TITLE
Measure LNA4ALL gain

### ISSUE THREAD

**Issue by acinonyx** [satnogs/satnogs-org#59]

**Comment by ppapadeas** [comment]
Attenuators missing

**Comment by zisi** [comment]
Measure LNA4All

In order to amplify the weak signal and reduce (as possible) the noise that captured by antenna we use the Low Noise Amplifier(LNA), LNA4all.

The LNA4all is connected in the output of antenna and in the input of receiver (as close as possible).
The properties of LNA4all are:

 Noise Figure: <1dB

 Gain: 11.5 - 23.5 dB

 Frequency range : 28kHz - 2.5GHz

 Power Suply: 6 - 12V or 5V (regulated) (we use 9V)

 The antenna input and output to receiver are matched to 50 ohms

 Low cost


We measure the LNA4all to confirm the above values. We used miniVNA Tiny and the 20dB attenuator.

The output signal (DUT) of minyVNA Tiny is 5.15dB after the LNA4all the signal may be ~25dB, but the maximum measured signal by minyVNA Tiny is 10dBm (10mW).
So we have problem to measure without use attenuator. With above case we decided to use 20dB attenuator.

20dB Attenuator

![uploads/026b1531-158e-4a01-add2-0270fbb35984/Attenuator 20dB.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F026b1531-158e-4a01-add2-0270fbb35984%2FAttenuator+20dB.png)


In below figures are presented the testing setup of LNA4all with attenuator and miniVNA and the measurements which is exported from the miniVNA.

Testing setup

![uploads/f4f38c6b-ee00-41b5-a0a7-12957e2876d8/lna4all_testing_setup.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff4f38c6b-ee00-41b5-a0a7-12957e2876d8%2Flna4all_testing_setup.jpg)

![uploads/7329c2b6-e65b-4906-a01c-f1a1e69b5604/LNA.jpeg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7329c2b6-e65b-4906-a01c-f1a1e69b5604%2FLNA.jpeg)

Measurements

![uploads/f28bdd56-5bd6-47eb-95a6-ebd3ba779e98/LNA 20dB Attenuator.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff28bdd56-5bd6-47eb-95a6-ebd3ba779e98%2FLNA+20dB+Attenuator.png)

The gain of the LNA4all in ~147MHz is 20dB+3.07dB-5.15dB = 17.92 dB

in ~283MHz is 20dB+3.33dB-5.15dB = 18.18 dB

in ~437MHz is 20dB+2.32dB-5.15dB = 17.17 dB

pad: https://pad.hackerspace.gr/p/LNApost

**Comment by ppapadeas** [comment]
r+ ready for publishing.
